spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #################### postgres Configuration #####################################
  datasource:
    url: jdbc:postgresql://localhost:5432/technicalcodingchallange
    username: postgres
    password: pgpassword



  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

    defer-datasource-initialization: true


